name: Latest Blog Posts
on:
  schedule:
    - cron: '0 * * * *' # 매 시간 0분에 실행
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: sarisia/actions-readme-feed@v1
        with:
          url: "https://norepinephrine.tistory.com/rss"
          file: "README.md"
          # 티스토리 보안 우회를 위한 필수 설정
          format: "- <a href='${url}' target='_blank'>${title}</a> (${date})"
          timezone: "Asia/Seoul"
